runtime: php
env: flex
runtime_config:
    document_root: .
env_variables:
    MYSQL_USER: "surveyadm"
    MYSQL_PASSWORD: "Election@2019"
    MYSQL_DSN: "mysql:dbname=surveyapp;unix_socket=/cloudsql/survey-2018ht12173:asia-south1:survey-cc"
beta_settings:
    cloud_sql_instances: "survey-2018ht12173:asia-south1:survey-cc"
